home:
  method: GET
  path: /
  controller: 'Nastoletni\Code\UserInterface\Web\Controller\PasteController:home'

create:
  method: POST
  path: /
  controller: 'Nastoletni\Code\UserInterface\Web\Controller\PasteController:create'

paste:
  method: GET
  path: /{id}/{key}
  controller: 'Nastoletni\Code\UserInterface\Web\Controller\PasteController:paste'
